### ISSUE TITLE
QEWD - Events missing data

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#33] opened 2017-06-09 08:53 UTC
Events heading - http://prntscr.com/fhpr9x - http://prntscr.com/fhbxvu - Event Name field (hosted as serviceTeam on the middleware level) is not being populated, when Event Type and Notes fields are missing on the middleware level.

**Comment by tony-shannon** [comment] 2017-06-20 15:06
Can I please get an update on this @robtweed 
thanks
T

**Comment by tony-shannon** [comment] 2017-06-26 13:45
thanks for update by email Rob

See update on AQL/Flat JSON  from @freshehr just received here
https://github.com/RippleOSI/Ripple-openEHR/issues/2#issuecomment-311052387 

@dkryvosheya Can we get the expected UI request/response structure please

**Comment by tony-shannon** [comment] 2017-06-27 16:27
@dkryvosheya we need update on the UI json payload & URL structure for GET & POSTs here please

**Comment by tony-shannon** [comment] 2017-06-28 15:46
@dkryvosheya  sorry to chase this again

**Comment by tony-shannon** [comment] 2017-06-29 07:28
response from @dkryvosheya ;

Response for  /api/patients/{patientId}/appointments/{sourceId}

    {
        author:"c4h_ripple_osi"
        dateCreated:1471513613105
        dateOfAppointment:1423440000000
        location:"Leeds General"
        serviceTeam:"${uniqueName}"
        source:"Marand"
        sourceId:"f12c293d-6edb-4c38-b52a-d086c23d0d3f"
        status:"Scheduled"
        timeOfAppointment:32400000
        eventType: "Appointment"
        eventNote: "sample note"
      }

**Comment by robtweed** [comment] 2017-06-30 13:20
OK - The events middle tier is in place.  It expects the following endpoints:

get summary list of all events for a patient:

GET /api/patients/9999999068/events

Returns an array of objects, each object being like this:

{
"dateCreated": 1494586220000,
"type": "Discharge",
"name": "Discharge to care home",
"description": "Needs nursing and supervisory care",
"dateTime": 1494496220958,
"source": "ethercis",
"sourceId": "93ac376d-3ff4-4e0b-b080-47eb3fe81750"
},

The first letter of the types are upper case, eg Admission, Discharge

To retrieve the detail for an event:

GET /api/patients/9999999068/events/93ac376d-3ff4-4e0b-b080-47eb3fe81750

To save a new event:

POST /api/patients/9999999068/events

The JSON payload should look similar to the GET response, eg:
{
  "name": "Discharge to care home",
  "type": "Discharge",
  "description": "Needs nursing and supervisory care",
  "dateTime": "2017-06-05T10:50:20.958Z",
  "author": "Dr Jason Donovan"
}

Note the POST'ed dateTime value should be in ISO date format as per example above

**Comment by dkryvosheya** [comment] 2017-07-04 08:27
Example of datetime picker: http://prntscr.com/fren1i

**Comment by freshehr** [comment] 2017-07-26 16:57
Can I get an update? I think there is still a design disconnect between the original requirement which was really just to carry an appointment event along with some appointment ? video consult data but in changing to 'generic events' the original use-case has been mangled. The problem is )I think) that QEWD is currently setup to expect one type of composition and AQL etc per heading but the requirement for events is to carry both

1, A generic event tracker composition that just says 'something happened'  with dates and a wee comment (the new requirement)
2. A very specific appointment composition with its own associated UI (the original requirement)

Now that is easy to do in openEHR - we can construct the AQL to pull back any composition with an event tracker on it but when we select the composition itself. the format of the composition,based on the parent template will be different, therefore QEWD has to handle 2 different composition formats per-heading.

The problem remains that the UI for an appointment event has in the past been very different from that of other kinds of event.

**Comment by tony-shannon** [comment] 2017-07-27 15:38
Not sure I understand that comment Ian , but from a UI test point of view this seems to be working ok now, 
ie we can add appointment and its being saved to etherCIS as far as I can see

![image](https://user-images.githubusercontent.com/939996/28679044-e6319314-72e9-11e7-8e5c-048eb22e30ca.png)

Does that help you?
Tony

**Comment by freshehr** [comment] 2017-07-27 15:42
Thanks Tony,

I noticed that Rob and Dmitri seemed to have sorted something out on a different issue thread. If you are happy that it is working as you want, so am I!!

**Comment by tony-shannon** [comment] 2017-07-27 15:50
yep , fine for now, will close this one

**Closed by tony-shannon** 2017-07-27 15:50 UTC
